apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-nfs-server-provisioner-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /export/volumes/data-nfs-server-provisioner-0
  storageClassName: nfs
  claimRef:
    namespace: kube-system
    name: data-nfs-provisioner-nfs-server-provisioner-0
