kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: exercise01:sre-team-vision-rb
  namespace: team-vision
subjects:
- kind: Group
  name: sre # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: exercise01:secrets-cr
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: exercise01:sre-api-rb
  namespace: team-api
subjects:
- kind: Group
  name: sre # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: exercise01:secrets-cr
  apiGroup: rbac.authorization.k8s.io
